# This is a basic workflow to help you get started with Actions

name: Create index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Run index creation
        run: |
           python .github/createIndex.py >> index.xml
           git status
           git config user.email "steinbusch@tema.de"
           git config user.name "Moritz"
           git add index.xml 
           git commit -m "Updated index"
           git push